%YAML:1.0

# flags
use_imu: 0
use_lidar: 0
use_navsat: 0
use_loop: 0             # 0 for only odometry, 1 for whole system
use_semantic: 0
use_adapt: 0
train: 0

# ros parameters
imu_topic: '/mynteye/imu/data_raw'
lidar_topic: '/lslidar_point_cloud'
# navsat_topic: '/kitti/oxts/gps/fix'
image0_topic: '/mynteye/left/image_raw'
image1_topic: '/mynteye/right/image_raw'
# color_topic: '/camera/color/image_raw'
result_path: '/home/jyp/Projects/lvio-fusion/result/result.csv'

# cameras parameters
undistort: 1

# camera0 intrinsics
camera0.fx: 3.6509624680337657e+02
camera0.fy: 3.6582107844466208e+02
camera0.cx: 3.7731877674972537e+02
camera0.cy: 2.3804064937753677e+02
camera0.k1: -2.9837705601814912e-01
camera0.k2: 7.5700979548022657e-02
camera0.p1: 1.7530605999019629e-04
camera0.p2: -5.4284812981307030e-04

# camera1 intrinsics
camera1.fx: 3.6401748092027668e+02
camera1.fy: 3.6417746726496523e+02
camera1.cx: 3.7559636500280993e+02
camera1.cy: 2.4903879600712332e+02
camera1.k1: -3.0803062161957084e-01
camera1.k2: 8.3487670591387161e-02
camera1.p1: -7.3109575503709556e-05
camera1.p2: -1.3285231720891767e-03

# lidar parameters
num_scans: 32           # only for 16, 32, 64
horizon_scan: 2000
ang_res_y: 1
ang_bottom: 16
ground_rows: 16
cycle_time: 0.1
min_range: 0.2
max_range: 20
deskew: 0
resolution: 0.5

#imu parameters
acc_n: 0.08             # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.004            # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.00004          # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-6           # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007         # gravity magnitude


# body to camera0
base_to_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [  0,  0,  1,  0,
            0, -1, -0,  -0.08,
            1,  0,  0,  0,
            0,  0, -0,  1]


# body to camera1
base_to_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [  0,  0,  1,  0,
            0, -1, -0,  0.08,
            1,  0,  0,  0,
            0,  0, -0,  1]

# body to lidar
base_to_lidar: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [  0,  0,  1,  0.16,
            0, -1, -0,  -0.035,
            1,  0,  0,  -0.117,
            0,  0, -0,  1]


# number of features
num_features: 200
num_features_init: 50
num_features_tracking_bad: 20
num_features_needed_for_keyframe: 80

# backend
windows_size: 3

# loop
relocator_mode: 1    # none = 0, visual = 1, lidar = 2, visual&&lidar = 3